export interface MovConDetFullDTO {
     id: number,
	 cedula: string,
	 nombre: string,
	 fecmovbco: Date,
	 recibo: string,
	 viadsc: string,
	 importe: number,
	 fecrec: Date,
	 referencia: string,
	 descripcion: string,
	 nucleoid: number,
	 nucleodsc: string,
	 mespago: string,
	 cantidad: number ,
	 notas: string,
}